const INCREMENT = 'ReduxTest/INCREMENT';

const GET_DATA_PENDING = 'ReduxTest/GET_DATA_PENDING';
const GET_DATA_SUCCESS = 'ReduxTest/GET_DATA_SUCCESS';
const GET_DATA_ERROR = 'ReduxTest/GET_DATA_ERROR';


export {
  INCREMENT,
  GET_DATA_PENDING,
  GET_DATA_SUCCESS,
  GET_DATA_ERROR
}
